version: '3'
services:
  ganache:
    image: trufflesuite/ganache:v7.7.7
    platform: linux/arm64
    ports:
      - 8545:8545
    command: --chain.chainId 1001 --chain.hardfork istanbul --database.dbPath /data --wallet.deterministic --chain.networkId 1001 --miner.blockTime 0
    volumes:
      - ganache_data:/data

volumes:
  ganache_data:
